# Premier exercice
Considérons le vecteur suivant :  __x__ = $\begin{bmatrix} 1 & 2 & 3 & 4 & 5\end{bmatrix}$
 
1. Créer ce vecteur à l’aide d’un tableau que l’on appellera `x`.
2. Afficher le type de `x` puis sa longueur.
3. Extraire le premier élément, puis en faire de même avec le dernier.
4. Extraire les trois premiers éléments et les stocker dans un vecteur que l’on nommera `a`.
5. Extraire les 1er, 2e et 5e éléments du vecteur (attention aux positions) ; les stocker dans un vecteur que l’on nommera `b`.
6. Additionner le nombre 10 au vecteur `x`, puis multiplier le résultat par 2.
7. Effectuer l’addition de `a` et `b`, commenter le résultat.
8. Effectuer l’addition suivante : `x+a` ; commenter le résultat, puis regarder le résultat de `a+x`.
9. Multiplier le vecteur par le scalaire `c` que l’on fixera à 2.
10. Effectuer la multiplication de `a` et `b` ; commenter le résultat.
11. Effectier la multiplication suivante : `x*a` ; commenter le résultats.
12. Récupérer les positions des multiples de 2 et les stocker dans un vecteur que l’on nommera `ind`, puis conserver uniquement les multiples de 2 de x dans un vecteur que l’on nommera `mult_2`.
13. Afficher les éléments de `x` qui sont multiples de 3 et multiples de 2.
14. Afficher les éléments de `x` qui sont multiples de 3 ou multiples de 2.
15. Calculer la somme des éléments de `x`.
16. Remplacer le premier élément de `x` par un 4.
17. Remplacer le premier élément de `x` par la valeur NaN, puis calculer la somme des éléments de `x`. 
18. Supprimer le vecteur `x`.

In [2]:
import numpy as np

In [41]:
# 1. Création du vecteur x
x = np.array((1,2,3,4,5))

In [4]:
# 2. Affichage du type de x et sa longueur
print("Type x:",type(x),"\nLongueur x:", len(x))

Type x: <class 'numpy.ndarray'> 
Longueur x: 5


In [6]:
# 3. Extraction du premier élèment et du dernier element
x[0], x[-1]

(1, 5)

In [73]:
# 4. Extraire les trois premiers éléments  et les stocker dans un vecteur que l’on nommera a.
a = x[0:3]
print(a)
# Extraire les trois premiers éléments et les stocker dans un vecteur a
a = x[:3]
print("Vecteur a :", a)

[1 2 3]
Vecteur a : [1 2 3]


In [21]:
# 5. Extraire les 1er, 2e et 5e éléments du vecteur 
b = [x[0], x[1], x[4]] # attention le type de b dans ce cas une une liste
print(b, type(b))

[1, 2, 5] <class 'list'>


In [24]:
b = x[[0,1,4]]  # attention le type de b dans ce cas un array
print(b, type(b))

[1 2 5] <class 'numpy.ndarray'>


In [25]:
# autre maniere
indices = [0,1,4]
b=x[indices]
# b = np.array(b)
print(b, type(b))

[1 2 5] <class 'numpy.ndarray'>


In [74]:
# 6. Additionner le nombre 10 au vecteur x, puis multiplier le résultat par 2.
x_plus_10 = (x + 10) * 2
print("Résultat de l'addition de 10 et la multiplication par 2 de x :", x_plus_10)

Résultat de l'addition de 10 et la multiplication par 2 de x : [22 24 26 28 30]


In [29]:
# 7. Effectuer l’addition de a et b, commenter le résultat
a+b

array([2, 4, 8])

In [42]:
# 8. Effectuer l’addition suivante : x+a ; commenter le résultat, puis regarder le résultat de a+x
x+a
# L'addition x + a ne peut pas être effectuée car les deux vecteurs n'ont pas la même taille.

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [43]:
a+x

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [75]:
# Multiplier le vecteur par le scalaire c que l’on fixera à 2
c = 2
mult_c = x * c
print("Résultat de la multiplication de x par le scalaire c :", mult_c)

Résultat de la multiplication de x par le scalaire c : [ 2  4  6  8 10]


In [76]:
# 10. Effectuer la multiplication de a et b ; commenter le résultat.
mult_ab = a * b
print("Résultat de la multiplication de a et b :", mult_ab)

Résultat de la multiplication de a et b : [ 1  4 15]


In [77]:
# 11. Effectier la multiplication suivante : x*a ; commenter le résultats.
mult_xa = x * a
print("Résultat de la multiplication de x et a :", mult_xa)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [ ]:
# 12. Récupérer les positions des multiples de 2 et les stocker dans un vecteur que l’on nommera ind, 
# puis conserver uniquement les multiples de 2 de x dans un vecteur que l’on nommera mult_2.

In [60]:
ind = np.where(x%2==0)
ind

(array([1, 3], dtype=int64),)

In [61]:
mult_2 = x[ind]
mult_2

array([2, 4])

In [67]:
# 13. Afficher les éléments de x qui sont multiples de 3 et multiples de 2.
# Trouver les indices des éléments multiples de 2 et de 3
indices = np.where((x % 2 == 0) & (x % 3 == 0))

# Afficher les éléments correspondants
print(x[indices])

[]


In [68]:
result = x[np.logical_and(x % 2 == 0, x % 3 == 0)]
print(result)

[]


In [70]:
# 14. Afficher les éléments de x qui sont multiples de 3 ou multiples de 2
indices = np.where((x % 2 == 0) | (x % 3 == 0))
print(x[indices])

[2 3 4]


In [71]:
result = x[np.logical_or(x % 2 == 0, x % 3 == 0)]
print(result)

[2 3 4]


In [80]:
# 15. Calculer la somme des éléments de x
print(sum(x))
somme_x = np.sum(x)
print("Somme des éléments de x :", somme_x)

15
Somme des éléments de x : 15


In [81]:
# 16. Remplacer le premier élément de x par un 4.
x[0]=4
print("Vecteur x après remplacement du premier élément par 4:", x)

[4 2 3 4 5]


In [90]:
# 17. Remplacer le premier élément de x par la valeur NaN, puis calculer la somme des éléments de x.
x = x.astype(dtype=float)
x[0] = np.nan
somme_x_nan = np.sum(x)
print("Somme des éléments de x après remplacement du premier élément par NaN :", somme_x_nan)

Somme des éléments de x après remplacement du premier élément par NaN : nan


In [91]:
# 18. Supprimer le vecteur x
del x

# Deuxième exercice
1. Créer la matrice suivante :
__A__ = $\begin{bmatrix} -3 & 5 & 6\\-1 & 2 & 2\\1 & -1 & -1 \end{bmatrix}$
2. Afficher la dimension de __A__, son nombre de colonnes, son nombre de lignes et sa longueur.
3. Extraire la seconde colonne de __A__, puis la première ligne.
4. Extraire l’élément en troisième position à la première ligne.
5. Extraire la sous-matrice de dimension 2x2 du coin inférieur de __A__, c’est-à-dire $\begin{bmatrix} 2 & 2 \\-1 & -1 \end{bmatrix}$
6. Calculer la somme des colonnes puis des lignes de __A__.
7. Afficher la diagonale de __A__.
8. Rajouter le vecteur $\begin{bmatrix} 1 & 2 & 3 \end{bmatrix}^T$ à droite de la matrice A et stocker le résultat dans un objet appelé __B__.
9. Retirer le quatrième vecteur de __B__.
10. Retirer la première et la troisième ligne de __B__.
11. Ajouter le scalaire 10 à __A__.
12. Ajouter le vecteur $\begin{bmatrix} 1 & 2 & 3 \end{bmatrix}^T$ à __A__.
13. Ajouter la matrice identité $I_3$ à __A__.
14. Diviser tous les éléments de la matrice __A__ par 2.
15. Multiplier la matrice __A__ par le vecteur ligne $\begin{bmatrix}1 & 2 & 3 \end{bmatrix}^T$.
16. Afficher la transposée de __A__.
17. Effectuer le produit avec transposition $A^TA$.

In [92]:
import numpy as np

In [139]:
# 1. Créer la matrice suivante : A
A = np.array([[-3, 5, 6],[-1, 2, 2], [1, -1, -1]])
print(A)

[[-3  5  6]
 [-1  2  2]
 [ 1 -1 -1]]


In [105]:
# 2. Afficher la dimension de A, son nombre de colonnes, son nombre de lignes et sa longueur.
print("Dimension de A :", A.)
print("Nombre de colonnes de A :", A.shape[1])
print("Nombre de lignes de A :", A.shape[0])
print("Longueur de A :", A.size)

Dimension de A : (3, 3)
Nombre de colonnes de A : 3
Nombre de lignes de A : 3
Longueur de A : 9


In [107]:
# 3. Extraire la seconde colonne de A, puis la première ligne.
#premiere colonne
deuxieme_colonne = A[:, 1]
premiere_ligne = A[0, :]
print("Deuxième colonne de A :", deuxieme_colonne)
print("Première ligne de A :", premiere_ligne)

Deuxième colonne de A : [ 5  2 -1]
Première ligne de A : [-3  5  6]


In [112]:
# 4. Extraire l’élément en troisième position à la première ligne
element_troisieme_position = A[0, 2]
print("Élément en troisième position de la première ligne :", element_troisieme_position)

Élément en troisième position de la première ligne : 6


In [117]:
# 5. Extraire la sous-matrice de dimension 2x2 du coin inférieur de A
sous_matrice = A[1:,1:]
print("Sous-matrice de dimension 2x2 :\n", sous_matrice)

Sous-matrice de dimension 2x2 :
 [[ 2  2]
 [-1 -1]]


In [118]:
# 6. Calculer la somme des colonnes puis des lignes de A
somme_colonnes = np.sum(A, axis=0)
somme_lignes = np.sum(A, axis=1)
print("Somme des colonnes de A :", somme_colonnes)
print("Somme des lignes de A :", somme_lignes)

Somme des colonnes de A : [-3  6  7]
Somme des lignes de A : [ 8  3 -1]


In [119]:
# 7. Afficher la diagonale de A
diagonale_A = np.diagonal(A)
print("Diagonale de A :", diagonale_A)

Diagonale de A : [-3  2 -1]


In [122]:
np.diag(diagonale_A)

array([[-3,  0,  0],
       [ 0,  2,  0],
       [ 0,  0, -1]])

In [133]:
# 8. Rajouter le vecteur [1 2 3]^T à droite de la matrice A et stocker le résultat dans un objet appelé B
B = np.hstack((A, np.array([[1, 2, 3]]).T))
print("Matrice B :\n", B)

Matrice B :
 [[-3  5  6  1]
 [-1  2  2  2]
 [ 1 -1 -1  3]]


In [134]:
# 9. Retirer le quatrième vecteur de B
B = B[:, :-1]
print("Matrice B après retirer le quatrième vecteur :\n", B)

Matrice B après retirer le quatrième vecteur :
 [[-3  5  6]
 [-1  2  2]
 [ 1 -1 -1]]


In [135]:
# 10. Retirer la première et la troisième ligne de B
B = B[[1], :]
print("Matrice B après retirer la première ligne :", B)

Matrice B après retirer la première ligne : [-1  2  2]


In [142]:
# 11. Ajouter le scalaire 10 à A
A += 10
print("Matrice A après ajout du scalaire 10 :", A)

Matrice A après ajout du scalaire 10 : [[ 7 15 16]
 [ 9 12 12]
 [11  9  9]]


In [137]:
# 12. Ajouter le vecteur [1 2 3]^T à A
A = np.hstack((A, np.array([[1, 2, 3]]).T))
print("Matrice A après ajout du vecteur [1 2 3]^T :", A)

Matrice A après ajout du vecteur [1 2 3]^T : [[ 7 15 16  1]
 [ 9 12 12  2]
 [11  9  9  3]]


In [146]:
# 13. Ajouter la matrice identité I3 à A
A += np.eye(3,dtype='int32')
print("Matrice A après ajout de la matrice identité :", A)

Matrice A après ajout de la matrice identité : [[ 8 15 16]
 [ 9 13 12]
 [11  9 10]]


In [153]:
# 14. Diviser tous les éléments de la matrice A par 2
# Convertir la matrice A en type float
A = A.astype(float)
A /= 2
print("Matrice A après division par 2 :\n", A)

Matrice A après division par 2 :
 [[1.   1.75 2.  ]
 [1.   1.5  1.5 ]
 [1.25 1.   1.25]]


In [158]:
# 15. Multiplier la matrice A par le vecteur ligne [1 2 3]^T
produit = A * np.array([[1, 2, 3]])
print("Produit de la matrice A par le vecteur [1 2 3] :\n", produit)

Produit de la matrice A par le vecteur [1 2 3] :
 [[1.   3.5  6.  ]
 [1.   3.   4.5 ]
 [1.25 2.   3.75]]


In [160]:
produit = np.dot(A, np.array([[1, 2, 3]]).T)
print("Produit de la matrice A par le vecteur [1 2 3]^T :\n", produit)

Produit de la matrice A par le vecteur [1 2 3]^T :
 [[10.5]
 [ 8.5]
 [ 7. ]]


In [161]:
# 16. Afficher la transposée de A
A_transpose = A.T
print("Matrice A transposée :", A_transpose)

Matrice A transposée : [[1.   1.   1.25]
 [1.75 1.5  1.  ]
 [2.   1.5  1.25]]


In [162]:
# 17. Effectuer le produit avec transposition A^TA
produit_transpose = np.dot(A_transpose, A)
print("Produit de A^TA :", produit_transpose)

Produit de A^TA : [[3.5625 4.5    5.0625]
 [4.5    6.3125 7.    ]
 [5.0625 7.     7.8125]]
