# Premier exercice

Considérons le vecteur suivant : `x = [1, 2, 3, 4, 5]`

1. Créer ce vecteur à l’aide d’un tableau que l’on appellera `x`.
2. Afficher le type de `x` puis sa longueur.
3. Extraire le premier élément, puis en faire de même avec le dernier.
4. Extraire les trois premiers éléments et les stocker dans un vecteur que l’on nommera `a`.
5. Extraire les 1er, 2e et 5e éléments du vecteur (attention aux positions) ; les stocker dans un vecteur que l’on nommera `b`.
6. Additionner le nombre 10 au vecteur `x`, puis multiplier le résultat par 2.
7. Effectuer l’addition de `a` et `b`, commenter le résultat.
8. Effectuer l’addition suivante : `x + a` ; commenter le résultat, puis regarder le résultat de `a + x`.
9. Multiplier le vecteur par le scalaire `c` que l’on fixera à 2.
10. Effectuer la multiplication de `a` et `b` ; commenter le résultat.
11. Effectuer la multiplication suivante : `x * a` ; commenter le résultat.
12. Récupérer les positions des multiples de 2 et les stocker dans un vecteur que l’on nommera `ind`, puis conserver uniquement les multiples de 2 de `x` dans un vecteur que l’on nommera `mult_2`.
13. Afficher les éléments de `x` qui sont multiples de 3 et multiples de 2.
14. Afficher les éléments de `x` qui sont multiples de 3 ou multiples de 2.
15. Calculer la somme des éléments de `x`.
16. Remplacer le premier élément de `x` par un 4.
17. Remplacer le premier élément de `x` par la valeur `NaN`, puis calculer la somme des éléments de `x`.
18. Supprimer le vecteur `x`.

In [7]:
import numpy as np

In [31]:
# 1. Créer ce vecteur à l’aide d’un tableau que l’on appellera `x`:

x = np.array([1, 2, 3, 4, 5], dtype='int8')
# x = np.array([1, 2, 3, 4, 5], dtype='float')

In [32]:
x

array([1, 2, 3, 4, 5], dtype=int8)

In [12]:
# 2. Afficher le type de x puis sa longueur.
print('Type de x:',type(x),',longueur de x:', len(x))

Type de x: <class 'numpy.ndarray'> ,longueur de x: 5


In [18]:
# 3. Extraire le premier élément, puis en faire de même avec le dernier.
print('premier element de x:',x[0])
print('dernier element de x:',x[len(x)-1])
print('dernier element de x:',x[-1])
print('dernier element de x:',x[4])

premier element de x: 1
dernier element de x: 5
dernier element de x: 5
dernier element de x: 5


In [34]:
# 4. Extraire les trois premiers éléments et les stocker dans un vecteur que l’on nommera a.
a = x[0:3]
a

array([1, 2, 3], dtype=int8)

In [38]:
# 5. Extraire les 1er, 2e et 5e éléments du vecteur (attention aux positions) ; 
# les stocker dans un vecteur que l’on nommera b.
indices = [0,1,4]
b = x[indices]
print('les 1er, 2e et 5e éléments du vecteur x sont:', b)

les 1er, 2e et 5e éléments du vecteur x sont: [1 2 5]


In [40]:
# 6. Additionner le nombre 10 au vecteur x, puis multiplier le résultat par 2.
resultat = (x+10)*2
print(resultat)

[22 24 26 28 30]


In [45]:
# Attention si on a une liste liste_x, on ne peut pas faire les opérations mathématique d'une façon directe comme
# on le fait sur les vecteurs
list_x = list(x)
(list_x)*2

In [48]:
# 7. Effectuer l’addition de a et b, commenter le résultat.
addition_a_b = a + b
addition_a_b

array([2, 4, 8], dtype=int8)

In [50]:
# 8. Effectuer l’addition suivante : x + a ; commenter le résultat, puis regarder le résultat de a + x
a + x

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [51]:
x + a

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [52]:
# 9. Multiplier le vecteur par le scalaire c que l’on fixera à 2.
c = 2 
multiplication_c = x * c
print('Le resultat de la muliplication par le scalaire c:', multiplication_c)

Le resultat de la muliplication par le scalaire c: [ 2  4  6  8 10]


In [53]:
type(multiplication_c)

numpy.ndarray

In [60]:
# 10. Effectuer la multiplication de a et b ; commenter le résultat.
a * b

array([ 1,  4, 15], dtype=int8)

In [64]:
# 11. Effectuer la multiplication suivante : x * a ; commenter le résultat.
x *  a

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [73]:
# 12. Récupérer les positions des multiples de 2 et les stocker dans un vecteur que l’on nommera ind, 
# puis conserver uniquement les multiples de 2 de x dans un vecteur que l’on nommera mult_2.
ind = np.where(x%2==0)
print(ind)
mult_2 = x[ind]
# mult_2 = x[x%2==0]
print(mult_2)

(array([1, 3]),)
[2 4]


In [74]:
%whos

Variable           Type       Data/Info
---------------------------------------
a                  ndarray    3: 3 elems, type `int8`, 3 bytes
addition_a_b       ndarray    3: 3 elems, type `int8`, 3 bytes
b                  ndarray    3: 3 elems, type `int8`, 3 bytes
c                  int        2
d                  ndarray    3: 3 elems, type `float64`, 24 bytes
ind                tuple      n=1
indices            list       n=3
list_x             list       n=5
mult               ndarray    3: 3 elems, type `float64`, 24 bytes
mult_2             ndarray    2: 2 elems, type `int8`, 2 bytes
multiplication_c   ndarray    5: 5 elems, type `int8`, 5 bytes
np                 module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
positions          tuple      n=1
resultat           ndarray    5: 5 elems, type `int8`, 5 bytes
x                  ndarray    5: 5 elems, type `int8`, 5 bytes


In [ ]:
# 13. Afficher les éléments de x qui sont multiples de 3 et multiples de 2.

In [78]:
mult_2_3 = x [(x%3 == 0) & (x%2 == 0)]
mult_2_3
mult_2_3 = x[np.logical_and((x%3 == 0),(x%2 == 0))]
mult_2_3

array([], dtype=int8)

In [83]:
np.logical_and((x%3 == 0),(x%2 == 0))

array([False, False, False, False, False])

In [80]:
# 14. Afficher les éléments de x qui sont multiples de 3 ou multiples de 2.
mult_2_ou_3 = x [(x%3 == 0) | (x%2 == 0)]
print(mult_2_ou_3)
mult_2_ou_3 = x[np.logical_or((x%3 == 0),(x%2 == 0))]
print(mult_2_ou_3)

[2 3 4]
[2 3 4]


In [81]:
x>=3

array([False, False,  True,  True,  True])

In [90]:
x =x.astype('float')

In [92]:
x.dtype

dtype('float64')

In [93]:
#Calculer la somme des éléments de x.
print(np.sum(x))
# Remplacer le premier élément de x par un 4.
x[0] = 4
print(x)
# Remplacer le premier élément de x par la valeur NaN, puis calculer la somme des éléments de x.
x[0] = np.NaN
print(np.sum(x))
# Supprimer le vecteur x.
del(x)

nan
[4. 2. 3. 4. 5.]
nan


In [94]:
y = np.array([[1,2,3],[4,np.NaN,6],[7,8,9]])

In [99]:
z = np.array([[1,2,3],[4,None,6],[7,8,9]])
z

array([[1, 2, 3],
       [4, None, 6],
       [7, 8, 9]], dtype=object)

In [96]:
y, y.dtype

(array([[ 1.,  2.,  3.],
        [ 4., nan,  6.],
        [ 7.,  8.,  9.]]),
 dtype('float64'))

In [100]:
z+y

TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

In [101]:
y+y

array([[ 2.,  4.,  6.],
       [ 8., nan, 12.],
       [14., 16., 18.]])

In [138]:
w = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,1,2],[4,2,6,4,1]])

In [151]:
t = 'text'

In [152]:
type(t)

str

In [158]:
w

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [7, 8, 9, 1, 2],
       [4, 2, 6, 4, 1]])

In [145]:
list = [1,2,3,'4',5]

In [147]:
w

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [7, 8, 9, 1, 2],
       [4, 2, 6, 4, 1]])

In [149]:
np.min(w), np.max(w)

(1, 9)

In [161]:
np.median(w)

4.0

In [ ]:
w.m

In [114]:
w = w.astype('float')

In [159]:
type(w)

numpy.ndarray

In [141]:
ww = w[0:5:2,0:5:2]
print(ww)

[[1 3 5]
 [7 9 2]]


In [129]:
ww = w[0:2,0:2]
ww

array([[9.5, 2. ],
       [4. , 5. ]])

In [121]:
w[0]

array([9.5, 2. , 3. ])

In [122]:
w[:,0]

array([9.5, 4. , 7. ])

In [125]:
w[1], w[1,:]

(array([4., 5., 6.]), array([4., 5., 6.]))

In [118]:
w[0,0]

9.5

In [ ]:
# 3. Extraire le premier élément, puis en faire de même avec le dernier:
    first_element = x[0]
    last_element = x[-1]
    print(first_element)  # 1
    print(last_element)   # 5


4. Extraire les trois premiers éléments et les stocker dans un vecteur que l’on nommera `a`:
    ```python
    a = x[:3]
    print(a)  # [1, 2, 3]
    ```

5. Extraire les 1er, 2e et 5e éléments du vecteur (attention aux positions) ; les stocker dans un vecteur que l’on nommera `b`:
    ```python
    b = [x[0], x[1], x[4]]
    print(b)  # [1, 2, 5]
    ```

6. Additionner le nombre 10 au vecteur `x`, puis multiplier le résultat par 2:
    ```python
    result = [(i + 10) * 2 for i in x]
    print(result)  # [22, 24, 26, 28, 30]
    ```

7. Effectuer l’addition de `a` et `b`, commenter le résultat:
    ```python
    addition_ab = [a[i] + b[i] for i in range(len(a))]
    print(addition_ab)  # [2, 4, 8]
    ```
    **Commentaire**: L'addition de `a` et `b` se fait élément par élément.

8. Effectuer l’addition suivante : `x + a` ; commenter le résultat, puis regarder le résultat de `a + x`:
    ```python
    addition_xa = x + a
    print(addition_xa)  # [1, 2, 3, 4, 5, 1, 2, 3]
    
    addition_ax = a + x
    print(addition_ax)  # [1, 2, 3, 1, 2, 3, 4, 5]
    ```
    **Commentaire**: En Python, l'opérateur `+` concatène les listes.

9. Multiplier le vecteur par le scalaire `c` que l’on fixera à 2:
    ```python
    c = 2
    x_multiplied = [i * c for i in x]
    print(x_multiplied)  # [2, 4, 6, 8, 10]
    ```

10. Effectuer la multiplication de `a` et `b` ; commenter le résultat:
    ```python
    multiplication_ab = [a[i] * b[i] for i in range(len(a))]
    print(multiplication_ab)  # [1, 4, 15]
    ```
    **Commentaire**: La multiplication de `a` et `b` se fait élément par élément.

11. Effectuer la multiplication suivante : `x * a` ; commenter le résultat:
    ```python
    multiplication_xa = [x[i] * a[i] for i in range(len(a))]
    print(multiplication_xa)  # [1, 4, 9]
    ```
    **Commentaire**: La multiplication de `x` et `a` se fait élément par élément pour les trois premiers éléments de `x` et `a`.

12. Récupérer les positions des multiples de 2 et les stocker dans un vecteur que l’on nommera `ind`, puis conserver uniquement les multiples de 2 de `x` dans un vecteur que l’on nommera `mult_2`:
    ```python
    ind = [i for i in range(len(x)) if x[i] % 2 == 0]
    mult_2 = [x[i] for i in ind]
    print(ind)    # [1, 3]
    print(mult_2) # [2, 4]
    ```

13. Afficher les éléments de `x` qui sont multiples de 3 et multiples de 2:
    ```python
    multiples_3_2 = [i for i in x if i % 3 == 0 and i % 2 == 0]
    print(multiples_3_2)  # []
    ```

14. Afficher les éléments de `x` qui sont multiples de 3 ou multiples de 2:
    ```python
    multiples_3_or_2 = [i for i in x if i % 3 == 0 or i % 2 == 0]
    print(multiples_3_or_2)  # [2, 3, 4]
    ```

15. Calculer la somme des éléments de `x`:
    ```python
    sum_x = sum(x)
    print(sum_x)  # 15
    ```

16. Remplacer le premier élément de `x` par un 4:
    ```python
    x[0] = 4
    print(x)  # [4, 2, 3, 4, 5]
    ```

17. Remplacer le premier élément de `x` par la valeur `NaN`, puis calculer la somme des éléments de `x`:
    ```python
    import math
    x[0] = math.nan
    sum_x_nan = sum(i for i in x if not math.isnan(i))
    print(sum_x_nan)  # 14
    ```

18. Supprimer le vecteur `x`:
    ```python
    del x
    # print(x)  # This will raise an error since x is deleted
    ```

IndentationError: unexpected indent (2367560067.py, line 2)

# Deuxième exercice

Créer la matrice suivante : 

1. Afficher la dimension de `A`, son nombre de colonnes, son nombre de lignes et sa longueur.
2. Extraire la seconde colonne de `A`, puis la première ligne.
3. Extraire l’élément en troisième position à la première ligne.
4. Extraire la sous-matrice de dimension 2×2 du coin inférieur de `A`, c’est-à-dire 
5. Calculer la somme des colonnes puis des lignes de `A`.
6. Afficher la diagonale de `A`.
7. Rajouter le vecteur `[1, 2, 3]⊤` à droite de la matrice `A` et stocker le résultat dans un objet appelé `B`.
8. Retirer le quatrième vecteur de `B`.
9. Retirer la première et la troisième ligne de `B`.
10. Ajouter le scalaire 10 à `A`.
11. Ajouter le vecteur `[1, 2, 3]⊤` à `A`.
12. Ajouter la matrice identité `I3` à `A`.
13. Diviser tous les éléments de la matrice `A` par 2.
14. Multiplier la matrice `A` par le vecteur ligne `[1, 2, 3]⊤`.
15. Afficher la transposée de `A`.
16. Effectuer le produit avec transposition `A⊤A`.
