# Getting Started with **Numpy**

Prénom:  
Nom:

## Import Numpy

In [3]:
from numpy import *

In [4]:
__version__

'1.26.4'

In [8]:
from numpy import \
array

## Simple array math

In [13]:
a = array([1,2,3,4])
b = array([2,3,4,5])

In [14]:
a+b

array([3, 5, 7, 9])

In [15]:
a*b

array([ 2,  6, 12, 20])

In [16]:
a**b

array([   1,    8,   81, 1024])

## Math Functions